---
title: "Toronto is Now Seeking Input on The Climate Actions Currently under Consideration."
subtitle: "Key areas where lifestyle changes can have a significant impact, including food, housing, and personal transportation."
author: 
  - Zixian He
thanks: "Code and data are available at: https://github.com/ZixianHe/starter-folder"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Since 2015, Canada is the only G7 country that has failed to reduce greenhouse gas emissions. In addition, as the country with the largest per capita greenhouse gas emissions in the world, the international pressure on Canada to reduce carbon emissions is increasing. The characteristics of economic energy demand at this stage make carbon emission reduction relatively difficult [@co2]. Therefore, formulating carbon emission reduction policies at this stage is the most urgent task of the Canadian government. This paper addresses the current net zero strategy  residents survey and aims to aim to figure out prioritize which climate actions should be implemented in the short term to make sure the city of Toronto meets its 2030 goals, which is reducing emissions by 65 percent from 1990 levels by 2030 [@data]. \\par\\textbf{Keywords:} Climate change, Net Zero Strategy, Buildings, Energy, Transportation, Waste, Decision-making"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)	
library(opendatatoronto)
library(dplyr)
 
data <- read.csv("/Users/eileen/Downloads/Raw data.csv",check.names = F)
```

# Introduction
Various global changes have plagued contemporary human beings, and people tend to think that climate change is the main cause of various global changes. Although global climate change is constrained by many large spatial factors, such as the relationship between the sun and the earth, the growing evidence shows that the factors of human activities can no longer be ignored [@ca1]. At the current level of understanding, scientists attribute the observed global warming effect to several gases, including carbon dioxide ($CO_2$), methane ($CH_4$), and nitrous oxide ($N_2O$), among others [@ca2]. These gases can absorb long-wave thermal radiation and increase the surface temperature, so they are called greenhouse gases.

Since the industrial Revolution, the frequent human activities have seriously threatened the climate change of global survival and development.According to the report released by the United Nations Intergovernmental Panel on Climate Change (IPCC) "Climate Change 2021: The Physical Science Basis", the global average temperature has risen by 1.1°C since the mid-1800s. This brings about many natural disasters, including melting glaciers, hot and heat waves, rainstorms and floods, and more unusual weather [@ca3]. The key to combating climate change is to control carbon emissions, and the only way is to achieve carbon peaks first and then achieve carbon neutrality. The federal government of Toronto has released a related plan "2030 Emissions Reduction Plan: Canada's Next Steps for Clean Air and a Strong Economy", which aims for a 40% reduction in emissions from 2005 levels by 2030 and advance Canada’s progress towards achieving net-zero emissions by 2050 [@ca4]. Many countries and enterprises in the world have also begun to set "net zero" goals to tackle climate change. Net zero, which balances greenhouse gas(GHG) removals and GHG emissions so that overall net emissions are zero. Achieving net zero is a daunting task.

While Prime Minister Justin Trudeau has repeatedly stressed that Canada can meet the Paris Agreement - will cut 30 percent of emissions in 2030 from 2005 levels, the United Nations believes Canada can accomplish less than 85 percent of its tasks. The French Climate Action Network also noted in a report that Canada's current climate change program will lead to global temperatures rising by more than 4 degrees Celsius [@ca5]. Data from Environment and Climate Change Canada shows that, fossil fuel emissions account for more than 80% of Canada's total emissions, and Canada's greenhouse gas emissions increased by 2% between 2017 and 2018. Between 2005 and 2018, GHG emissions from Canada’s oil and gas industry increased by 23 per cent from 158 million tonnes to 193 million tonnes; the oil and gas industry’s share of Canada’s total emissions increased by 5% during this period That’s a 27% increase, overtaking transportation as Canada’s largest source of emissions, with oil sands undoubtedly playing a “key role [@ca6].” Therefore, Canada seems to be caught in a weird logical cycle. First of all, in order to achieve the net zero emission reduction target, energy conversion is one of the important measures, but this measure undoubtedly requires a lot of financial support, and the revenue from the oil sands project will play an important role in Canada energy transformation. Secondly, the implementation of net zero emission reduction also requires a large amount of capital investment. The reduction of financial support will undoubtedly push the difficulty of net zero task to a higher level.

Support for carbon emission reduction actions is now inseparable from government initiatives and policy making. But it seems not easy to ensure that policy plans proceed as scheduled. For example, the United States signed the "Paris Agreement" on April 22,2016, during the Obama administration. In June 2017, the Trump administration, which repeated the slogan "MAGA" (Make America great again), announced the US withdrawal from the "Paris Agreement." That same year, it announced that it would abolish the Clean Power Plan and replace it with affordable energy programs. The move is intended to burden environmental policies on businesses and increase employment by increasing the consumption of fossil fuels [@us1]. In 2021, the Biden administration promised that the United States would return to the "Paris agreement" and proposed the goal of de-carbonizing electricity by 2035 and achieve net zero greenhouse gas emissions by 2050. To achieve the "30/50" goal, the Biden administration plans to spend 3 billion dollars on the climate plan [@us2]. On March 30, 2022, Canada's federal government has announced an emissions reduction plan involving $9.1 billion in new investment. The plan involves a number of measures, including building charging infrastructure, providing financial support to promote zero-emission vehicle sales, supporting clean medium and heavy-duty transportation projects, advancing the implementation of net-zero emissions on the grid, and more [@ca4].

In response to City Council’s climate emergency declaration in 2019, aims to figure out prioritize which climate actions should be implemented in the short term to make sure the city of Toronto meets its 2030 goals, the City of Toronto took a survey asking for feedback. The consultation also asked residents to consider what these actions might look like in the community. These actions include building, energy, transportation, Sustainable Consumption & Waste, Green-space, Decision-Making and Equitable Engagement. I also would like to talk about if gender, age, income will influence the actions that people choose [@data]. In addition, given that the implementation of the new policy will have an impact on the lives of the people, whether the age, income, and gender of the participants will have an impact on the outcome of climate action decisions will also be discussed.


# Data





# Model


Here's a dumb example of how to use some references: In paper we run our analysis in `R` [@citeR]. 



# Results

# Discussion

## First discussion point

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


